### ISSUE TITLE
Ragnarok is not closing 

### ISSUE THREAD

**Issue by Necklaces** [gdprcasualties/gdprcasualties.github.io#2]
https://forum.ragnarokeurope.com/ro/index.php?/topic/84441-regarding-the-rumours-about-server-close/

But they will be blocking EU IPs

> iRO has officially announced that a restriction of ip addresses will block European players in the future from their servers. And it seems that this website somehow mixed things up. Our servers will not close. We do warmly welcome every European iRO player who decides to start a new Ragnarok journey on our server!

**Comment by gdprcasualties** [comment]
This is within the scope of GDPR casualties which include denial of service to European users.
