### ISSUE TITLE
Instapaper seems to tempararly block EU

### ISSUE THREAD

**Issue by etu** [gdprcasualties/gdprcasualties.github.io#5]
Found this in my newsfeed:
https://kopitiambot.com/2018/05/24/instapaper-is-temporarily-shutting-off-access-for-european-users-due-to-gdpr/

But I'm to lazy to fork and make a PR at the moment.

**Comment by gdprcasualties** [comment]
I saw this as well. I am only cataloguing sites that are not working to implement GDPR compliance and have no definite timeline for when they will start. Thanks for your suggestion.
